CREATE DATABASE IF NOT EXISTS CustomerDetails;
CREATE DATABASE IF NOT EXISTS resturant;
CREATE DATABASE IF NOT EXISTS MenuItems;
CREATE DATABASE IF NOT EXISTS OrderService;
CREATE DATABASE IF NOT EXISTS PaymentService;
